### ISSUE TITLE
As a Geobank data-collector or web-service developer, I want to have a quick-build script that setups all components of the Geobank to start development easily.

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#26]

**Comment by Piiit** [comment]
Done. @bertolla @stefanodavid Please test on our development branch... just checkout that branch and run .../quickbuild.sh... See comments inside that script for details.

**Comment by stefanodavid** [comment]
Well, this issue was already closed, but I tested again the latest version of the script by @Piiit and, except for a few, minor corner cases, it works. I will add some more information in the troubleshooting section of the dedicated howto to keep track of those cases and discuss with him if there are further changes to be done to the script.

**Comment by Piiit** [comment]
I tested it again on a new Debian 9 machine, and fixed some more issues regarding maven-surefire-plugin configuration failing to run tests on certain Java versions. Now everything should work. I move it to Done now, if we find new bugs we could file an issue here.

**Comment by stefanodavid** [comment]
@Piiit on an Ubuntu 18.04 LTS and openjdk 11 the script fails silently. The system must be configured java 8 manually with
`update-alternatives --config java`
provided that openjdk-8-jre-headless is installed (luckily enough, 8 and 11 can coexist on the system :smiley: ).

As for 42ed084, yes it works - I changed my local copy exactly like that to make it work on postgresql 9.5.

I added a warning on the
