### ISSUE TITLE
As a maintainer of the Big Data Platform v2, I want to use all web services as in v1

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#50]
Belongs to the EPIC #28

- [x] Create a clone of our production Postgres server
- [x] Migrate all data to the new schema
- [x] Create necessary indexes
- [x] Deploy reader V2 to our test server
- [x] Deploy all webservices (v2) to our test server
- [x] Change v1 to allow various schema names (prerequisite for comparison)
- [x] Write a script that executes the same API calls to the old and the new reader and webservice interface and compares the result (it must be the same incl. a similar performance)
- [x] Test responses of all REST methods for similarity between V1 and V2, create a list of differences and discuss if they must be fixed or can be kept as-is
- [x] CI for bdp-api v2 fails - fix that
- [x] Run tests against bdp-api as well
- [x] Setup a clone of mobility.meran.eu to check correctness and find issues in data retrievals
> See http://mobilityv2.meran.eu.s3-website-eu-west-1.amazonaws.com/
- [x] Setup a clone of analytics.mobility.bz.it to check correctness and find issues in data retrievals
> See https://tomcatsec.testingmachine.eu/analytics2/

**Comment by Piiit** [comment]
Listing relevant differences between APIs... 
```
https://tomcatsec.testingmachine.eu/reader/station-details {'stationType': 'Environmentstation', 'stationId': 'AB2'}
http://127.0.0.1:8081/reader/station-details {'stationType': 'Environmentstation', 'stationId': 'AB2'}

TIMING  : 0.000000 (same ::: 0.00%)

ENCODING: UTF-8 vs. UTF-8

STATUS  : 200 vs. 200

  [
      {
          "id": "AB2"
-         "latitude": 46.3436527777778
?                            ^^^^^^^^^
+         "latitude": 46.343611
?                            ^^
-         "longitude": 11.2793333333333
?                               -------
+         "longitude": 11.279333
+         "municipality": "Auer - Ora"
          "name": "Autostrada Sud - Egna"
      }
  ]
RESPONSES are different (NB: ignore rules applied)
```

**Comment by Piiit** [comment]
@bertolla @rcavaliere @ohnewein 
Version 2.0 is online and ready for testing... You can use the two tools mentioned in the introduction of this user story to test... performance could be an issue for now, since I do not have all indexes ported to V2 yet. I will let you know when performance testing can be conducted.

**Comment by bertolla** [comment]
tested it with mocha and everything worked fine. We must remember to also port carpooling since it became relevant again recently.

**Comment by rcavaliere** [comment]
@Piiit I have made some tests. Here my comments:

-[] I can not see the details of the e-mobility stations. I think that there is some issues related to the stations that are children of other stations (see plug -> station). Also on analytics I just see a couple of stations... is this known / intended or is there a problem here?
-[] for the parking stations, some metadata that have for the parking stations of Bolzano is not visualized anymore. With the current snapshot, I can not see if the data of Trento and Rovereto is correct, because at the time we didn't have these datasets.
-[] for the air quality stations, the same as the point above applies with the new stations in Trentino and the open data in South Tyrol, so I can't check this.
-[] for the rwis stations, I get a 502 error from analytics. Did you forget to include this dataset in the API?
-[] analytics has some issues related the visualization of data on the plots (it always get a 504 error). I fear this is an application issue (Chris told me that the we need to give more RAM to the machine on which it is installed, otherwise it does not work properly....).

I would suggest to make a second testing phase in which we compare the current system with the new system working in real-time. This would significantly simplify the comparison and highlight errors. Is this possible?

**Comment by bertolla** [comment]
I set up parking.bz.it for v2 to see if parking is working correctly:
http://it.bz.parking-bdpv2.s3-website-eu-west-1.amazonaws.com

There are some obvious flaws, like municipality, but the biggest problem is that the test database for ws does not contain datasets which are up to date and therefore a lot of stuff is not even displayed

**Comment by bertolla** [comment]
bluetooth gives some strange proxy error. I guess it happens because the querry times out: http://tomcat.testingmachine.eu/bluetooth2/rest/get-records?station=proma&name=Bluetooth%20Count%20record&seconds=60000000

**Comment by Piiit** [comment]
@bertolla 

> bluetooth gives some strange proxy error. I guess it happens because the querry times out: http://tomcat.testingmachine.eu/bluetooth2/rest/get-records?station=proma&name=Bluetooth%20Count%20record&seconds=60000000

It gives a timeout, since the data is huge... try with `seconds=10000000`

**Comment by Piiit** [comment]
@rcavaliere FYI

> I set up parking.bz.it for v2 to see if parking is working correctly:
> http://it.bz.parking-bdpv2.s3-website-eu-west-1.amazonaws.com
> 
> There are some obvious flaws, like municipality, and also that stuff which is in the database is not being shown like trentos data

@bertolla fixes this issue for now inside the dc-interface. Data collectors overwrite existing municipalities or send them in a non-standard format. We create a hack for now, to overwrite them with Patrick's tool. However, we need to think about a general solution for V3....

**Comment by Piiit** [comment]
@rcavaliere @bertolla 
V2 is online and running. We need now to check, if all webservices publish correct data over time. I would therefore suggest to set this user story as done, and open new bug reports if necessary.
